on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: pandiff pr
    steps:
      - name: Hello world
        id: hello
        uses: carafelix/simple-pandiff-action@fb429a981780452a896a098c1886871e876f71a6

      # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "${{ steps.hello.outputs.diffs }}"
