on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: pandiff pr
    steps:
      - name: Hello world
        id: hello
        uses: carafelix/simple-pandiff-action@ed917674aff90d890ade2fb941d1141915961cdb

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "${{ steps.hello.outputs.diffs }}"
