on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: pandiff pr
    steps:
      - name: Hello world
        id: hello
        uses: carafelix/simple-pandiff-action@56b000a0043bb26d4af4e49cab339d898249240f

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "${{ steps.hello.outputs.diffs }}"
